### PR TITLE
10: Wiki Collaborators

### PR DESCRIPTION
**Pull request by dogweather**
Here's [the checkpoint](https://www.bloc.io/users/beth-gilomen/checkpoints/1048?roadmap_section_id=16)

### CODE REVIEW

**Comment by dogweather** [comment]
I just realized why you had titled this with _16_. I see it in the URL ... although the html page for this checkpoint says 10.

**Comment by dogweather** [comment]
Hey @gilomen2 what ruby version are you using for this? We should add it into the gemfile.

**Comment by gilomen2** [comment]
@dogweather 2.2.1

**Comment by gilomen2** [comment]
her @dogweather, i actually managed to solve the problem myself.  there were several issues, but the main one was that i was using <% form_for instead of <%= form_for, so the form wasn’t rendering at all. So sorry to waste your time!

**Comment by dogweather** [comment]
No problem. Geez, yeah, that Rails `form_for` API is annoying ... it's gone through a lot of changes, and subtle errors like that one are easy to make.

**Pull request closed without merging**
